### ISSUE TITLE
OpenBSD Vagrant up hangs

### ISSUE THREAD

**Issue by miguescri** [fnichol/packer-templates#4] opened 2021-06-04 14:17 UTC
I'm trying to spin up a `fnichol/openbsd-6.9` box with Vagrant, but `vagrant up` hangs when attemping to connect via SSH. I must be messing something up in the Vagrantfile, even though I've added the parameters in https://github.com/fnichol/packer-templates/blob/master/vagrantfile_templates/openbsd.rb

Vagrant version: 2.2.16
Virtualbox version: 6.1.22

Vagrantfile:

```ruby
NODES = [
  { hostname: 'p1', type: "proxy", ip: '192.168.1.80', mem: 500 },
]

Vagrant.configure("2") do |config|
    NODES.each do |node|
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.hostname = node[:hostname]
            if node[:type] == "proxy"
                nodeconfig.vm.box = "fnichol/openbsd-6.9"
                nodeconfig.ssh.shell = "/bin/sh"
                nodeconfig.ssh.sudo_command = "doas %c"
                nodeconfig.vm.synced_folder ".", "/vagrant",
                  type: "rsync",
                  rsync__rsync_path: "doas rsync"
            else
                nodeconfig.vm.box = "generic/ubuntu2004"
            end

            nodeconfig.vm.provider "virtualbox" do |v|
                v.memory = node[:mem]
                v.cpus = 1
                v.default_nic_type = "virtio"
                v.linked_clone = true
                v.customize ["modifyvm", :id, "--name", node[:hostname]]
            end
            
            nodeconfig.vm.boot_timeout = 400
        end
    end
end
```

Output of `vagrant up`:

```
Bringing machine 'p1' up with 'virtualbox' provider...
==> p1: Cloning VM...
==> p1: Matching MAC address for NAT networking...
==> p1: Checking if box 'fnichol/openbsd-6.9' version '20210523.1716.0' is up to date...
==> p1: Setting the name of the VM: OpenBSD-load-balancer_p1_1622813402581_18383
==> p1: Clearing any previously set network interfaces...
==> p1: Preparing network interfaces based on configuration...
    p1: Adapter 1: nat
==> p1: Forwarding ports...
    p1: 22 (guest) => 2222 (host) (adapter 1)
==> p1: Running 'pre-boot' VM customizations...
==> p1: Booting VM...
==> p1: Waiting for machine to boot. This may take a few minutes...
    p1: SSH address: 127.0.0.1:2222
    p1: SSH username: vagrant
    p1: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

The virtualbox GUI shows the machine initializes completely up to the login prompt.

**Comment by fnichol** [comment] 2021-06-19 18:53
Hi there @miguescri! Sorry I missed this, but yes, I can confirm what you're seeing with the setup above.

Good news is that it looks like the solution is reasonably straight forward.

The Packer built base box for OpenBSD was created with the Intel Pro/1000 MT Desktop network interface, and it looks like the VM didn't come up when the `default_nic_type` was set to `"virtio"`. At this point I've made these OpenBSD boxes for so long (over 5 or 6 years by the looks of things) that I can't remember if that was an intentional choice due to what worked, or an oversight that might work today (as far as I know OpenBSD likely supports virtio networking in a guest but would have to confirm).

So to summarize, you should be able to either remove the `v.default_nic_type = "virtio"` line, or make it conditional on your `:type`.

If you want a few less lines of setup, you can also remove the customizing of the OpenBSD machine as the Vagrant box ships with those as defaults for the box. In other words, this should work identically with the virtio tweak:

```ruby
NODES = [
  { hostname: 'p1', type: "proxy", ip: '192.168.1.80', mem: 500 },
]

Vagrant.configure("2") do |config|
    NODES.each do |node|
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.hostname = node[:hostname]
            if node[:type] == "proxy"
                nodeconfig.vm.box = "fnichol/openbsd-6.9"
            else
                nodeconfig.vm.box = "generic/ubuntu2004"
            end

            nodeconfig.vm.provider "virtualbox" do |v|
                v.memory = node[:mem]
                v.cpus = 1
                v.default_nic_type = "virtio" unless node[:type] == "proxy"
                v.linked_clone = true
                v.customize ["modifyvm", :id, "--name", node[:hostname]]
            end

            nodeconfig.vm.boot_timeout = 400
        end
    end
end
```

Hope this helps and assuming it does, I'll close this out. If I'm wrong, we can re-open and look further. I tend to use the VMware Fusion version of these boxes so thank you for confirming it's worth making the VirtualBox versions too!

**Closed as completed by fnichol** 2021-06-19 18:53 UTC
Labels: question

**Comment by miguescri** [comment] 2021-06-20 08:42
Thank you very much, @fnichol ! I confirm the workaround works an I'm now able to SSH into the box.
